variables:
  GIT_SSL_NO_VERIFY: "true"

mirror_job:on-schedule:
  image: robotgraves/curl-git
  only:
    # - schedules
  script: |
    apk update
    apk add perl openssh-client

    if [ ! -z "${IDENTITY_FILE}" ]; then
      mkdir -p ~/.ssh
      echo "${IDENTITY_FILE}" > ~/.ssh/id_rsa
      chmod og-rwx ~/.ssh/id_rsa
    fi

    # derive GITLAB_HOST from CI_PROJECT_URL
    GITLAB_URL_PROTO="$(echo ${CI_PROJECT_URL} | sed -e's,^\(.*://\).*,\1,g')"
    PARSED_GITLAB_URL="$(echo ${CI_PROJECT_URL/${GITLAB_URL_PROTO}/})"
    GITLAB_HOST="$(echo ${PARSED_GITLAB_URL} | cut -d/ -f1)"

    # ignore host checking for GITLAB_HOST
    echo -e "Host ${GITLAB_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

    # clone everything from github and push to gitlab
    git clone --bare https://github.com/romain-grecourt/fileupload-webapp.git
    cd fileupload-webapp.git
    git push --mirror $(echo ${CI_REPOSITORY_URL} | perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#')