variables:
  GIT_SSL_NO_VERIFY: "true"

mirror_job:on-schedule:
  image: robotgraves/curl-git
  only:
    # - schedules
  script: |
    apk update
    apk add perl openssh-client

    # clone everything from github
    git clone --bare https://github.com/romain-grecourt/fileupload-webapp.git
    cd fileupload-webapp.git

    # derive GITLAB_HOST from CI_PROJECT_URL
    GITLAB_URL_PROTO="$(echo ${CI_PROJECT_URL} | sed -e's,^\(.*://\).*,\1,g')"
    PARSED_GITLAB_URL="$(echo ${CI_PROJECT_URL/${GITLAB_URL_PROTO}/})"
    GITLAB_HOST="$(echo ${PARSED_GITLAB_URL} | cut -d/ -f1)"

    git push --mirror $(echo ${CI_REPOSITORY_URL} | perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#')
    echo -e "Host ${GITLAB_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config